//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryExample_15_02_22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hareket
    {
        public int ID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> Tutar { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
